### ISSUE TITLE
是否可以添加-y选项

### ISSUE THREAD

**Issue by lookforwardxu** [d3ckx1/Fvuln#15]
多IP扫描时，爆破SSH、redis等之前需要手动输入y或n来确认，是否可以添加-y选项来自动确认

**Comment by d3ckx1** [comment]
已经加入10秒无操作，自动进行爆破操作，在下一次更新的版本里

**Comment by lookforwardxu** [comment]
> 已经加入10秒无操作，自动进行爆破操作，在下一次更新的版本里

OK，感谢大佬
